### ISSUE TITLE
一点点小小建议

### ISSUE THREAD

**Issue by uuk020** [liaoshengping/express-sdk#1]
引入GuzzleHttp\Client并没有用到, 只抛出ClientException 这个异常,  感觉有点奇怪.  我是因为不想用这个包, 太大了. 对于快递查询 来说有点小题大做,  所以另外封装一个.  

另外我觉得把.idea忽略掉比较好. 共勉

**Comment by wzhanjun** [comment]
怎么看作者的这个包都像抄袭你的啊， format 的方法都一样

**Comment by liaoshengping** [comment]
@uuk020 非常感谢您的建议，后面开发的时候，会注意这些细节

**Comment by liaoshengping** [comment]
@wzhanjun 感谢你的回答，这个包主要是学习一下 @uuk020  的封装思路，以后有能力了，会产出原创的作品

**Comment by uuk020** [comment]
> 怎么看作者的这个包都像抄袭你的啊， format 的方法都一样
 
我的协议是MIT, 他引用我的文件有注释我名称. 所以没有关系的.

**Comment by uuk020** [comment]
> @uuk020 非常感谢您的建议，后面开发的时候，会注意这些细节

共勉, 我觉得我代码封装的一般. 还是没有@overtrue @finecho 封装的好.

**Comment by overtrue** [comment]
@uuk020 加油，别着急，慢慢积累就好了，我也是写了几十万行代码才写得稍微顺一些的，不是一蹴而就的。
