### ISSUE TITLE
有接口地址的文档吗？

### ISSUE THREAD

**Issue by fastknifes** [liaoshengping/express-sdk#2]
http://sp0.baidu.com/9_Q4sjW91Qh3otqbppnN2DJv/pae/channel/data/asyncqury?appid=4001&com=&nu=
大佬这个地址怎么抓到的？有文档吗

**Comment by liaoshengping** [comment]
> http://sp0.baidu.com/9_Q4sjW91Qh3otqbppnN2DJv/pae/channel/data/asyncqury?appid=4001&com=&nu=
> 大佬这个地址怎么抓到的？有文档吗

这个是蹭百度的。发现另外一种蹭百度物流的方式，已更新
