### ISSUE TITLE
好像不行啊

### ISSUE THREAD

**Issue by Jamesccvv** [liaoshengping/express-sdk#3]
返回array(1) {
  ["kkk"]=>
  array(3) {
    ["channel"]=>
    string(3) "kkk"
    ["status"]=>
    string(12) "获取失败"
    ["exception"]=>
    string(15) "渠道不存在"
  }
}

**Comment by liaoshengping** [comment]
> 返回array(1) {
> ["kkk"]=>
> array(3) {
> ["channel"]=>
> string(3) "kkk"
> ["status"]=>
> string(12) "获取失败"
> ["exception"]=>
> string(15) "渠道不存在"
> }
> }

渠道写 baidu 试试
